sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-dns-server-image .
script:
  # the "yast-travis-ruby" script is included in the base yastdevel/ruby image
  # see https://github.com/yast/docker-yast-ruby/blob/master/yast-travis-ruby
  - docker run -it -e TRAVIS=1 --privileged -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" yast-dns-server-image yast-travis-ruby
